import { loadConfig } from "@easyploy/config";
import { intro, outro, spinner } from "@easyploy/ui";
import { exec } from "child_process";
import { promisify } from "util";
import path from "path";
import fs from "fs/promises";

const execAsync = promisify(exec);

export async function cmdDeploy(opts: Record<string, unknown>): Promise<void> {
  const configPath = (opts.config as string) || "easyploy.config.json";
  const nonInteractive = opts.nonInteractive as boolean;
  
  intro("🚀 Deploying with easyploy");
  
  const s = spinner();
  s.start("Loading configuration...");
  
  try {
    // Load config
    const config = await loadConfig(configPath);
    s.stop(`Configuration loaded: ${config.project.name}`);
    
    // Determine stack and create deployment plan
    const stack = config.stack?.name || "custom";
    console.log(`Stack: ${stack}`);
    console.log(`Template: ${config.workflow?.template || "custom"}`);
    
    // Create docker-compose based on stack
    s.start("Generating deployment files...");
    await generateDeploymentFiles(config);
    s.stop("Deployment files generated");
    
    // Deploy
    if (!nonInteractive) {
      console.log("\n📋 Deployment Plan:");
      console.log(`  Project: ${config.project.name}`);
      console.log(`  Stack: ${stack}`);
      console.log(`  Stages: ${config.workflow?.stages?.join(", ") || "build, deploy"}`);
      console.log();
    }
    
    // Execute deployment
    s.start("Deploying to server...");
    
    // In a real implementation, this would:
    // 1. SSH to server
    // 2. Copy files
    // 3. Run docker-compose up
    // 4. Health check
    
    // For now, simulate with local docker-compose
    try {
      await execAsync("docker-compose -f docker-compose.easyploy.yml up -d");
      s.stop("Deployment successful!");
    } catch (error) {
      s.stop("Deployment failed");
      console.error("Error:", error);
      throw error;
    }
    
    outro(`✅ ${config.project.name} deployed successfully!`);
    
  } catch (error) {
    s.stop("Deployment failed");
    console.error("❌ Deployment error:", error);
    process.exit(1);
  }
}

async function generateDeploymentFiles(config: any): Promise<void> {
  const stack = config.stack?.name || "custom";
  
  // Generate docker-compose based on stack
  const dockerCompose = generateDockerCompose(stack, config);
  await fs.writeFile("docker-compose.easyploy.yml", dockerCompose);
  
  // Generate Dockerfile if needed
  const dockerfile = generateDockerfile(stack);
  await fs.writeFile("Dockerfile.easyploy", dockerfile);
}

function generateDockerCompose(stack: string, config: any): string {
  const baseServices: Record<string, any> = {
    app: {
      build: {
        context: ".",
        dockerfile: "Dockerfile.easyploy",
      },
      ports: ["3000:3000"],
      environment: [
        "NODE_ENV=production",
      ],
      restart: "unless-stopped",
    },
  };
  
  // Add stack-specific services
  if (stack === "nhost" || stack === "supabase") {
    baseServices.postgres = {
      image: "postgres:15-alpine",
      environment: {
        POSTGRES_USER: "postgres",
        POSTGRES_PASSWORD: "postgres",
        POSTGRES_DB: "app",
      },
      volumes: ["postgres_data:/var/lib/postgresql/data"],
      ports: ["5432:5432"],
    };
    
    baseServices.volumes = {
      postgres_data: null,
    };
  }
  
  if (stack === "nhost") {
    baseServices.hasura = {
      image: "hasura/graphql-engine:v2.0.0",
      ports: ["8080:8080"],
      environment: {
        HASURA_GRAPHQL_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/app",
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true",
        HASURA_GRAPHQL_ADMIN_SECRET: "admin-secret",
      },
      depends_on: ["postgres"],
    };
  }
  
  return `# Generated by easyploy
version: '3.8'

services:
${Object.entries(baseServices)
  .filter(([key]) => key !== "volumes")
  .map(([name, service]) => {
    const serviceYaml = Object.entries(service)
      .map(([k, v]) => {
        if (Array.isArray(v)) {
          return `    ${k}:\n${v.map((item) => `      - ${item}`).join("\n")}`;
        }
        if (typeof v === "object" && v !== null) {
          return `    ${k}:\n${Object.entries(v)
            .map(([vk, vv]) => `      ${vk}: ${vv}`)
            .join("\n")}`;
        }
        return `    ${k}: ${v}`;
      })
      .join("\n");
    return `  ${name}:\n${serviceYaml}`;
  })
  .join("\n\n")}

${baseServices.volumes ? `volumes:\n${Object.keys(baseServices.volumes).map(v => `  ${v}:`).join("\n")}` : ""}
`;
}

function generateDockerfile(stack: string): string {
  return `# Generated by easyploy
FROM node:20-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production

# Copy source
COPY . .

# Build (if needed)
RUN npm run build 2>/dev/null || true

# Expose port
EXPOSE 3000

# Start command
CMD ["npm", "start"]
`;
}
